# print('Hello world!')
# print('Salom Dunyo!')
# print('Mening vatanim O\'zbekiston')
# print('Welcome to Python!')
# print(5+9)
# print('Assalomu aleykum')
# print(2+2*2)
# print(19/5)
# print(2**5)
